# -------- DAILY REPORT SCHEDULE --------
REPORT_CRON_HOUR = 22
REPORT_CRON_MINUTE = 0

# -------- TEMPLATE VERSIONS --------
REPORT_TEMPLATE_VERSION = "1.0"

# -------- AGENT LIMITS --------
TGA_DAILY_LIMIT = 25
ADS_SYNC_INTERVAL_MIN = 60
