# app/agents/tiktok_growth/TGA_Main_Brain_manager.py

from dataclasses import dataclass, field
from typing import List, Dict, Any
import datetime


@dataclass
class TGAVideoDraft:
    """Represents a single video idea or draft before posting."""
    id: str
    title: str
    caption: str
    status: str  # "draft" | "approved" | "rejected" | "posted"
    created_at: datetime.datetime = field(default_factory=datetime.datetime.utcnow)
    meta: Dict[str, Any] = field(default_factory=dict)


class TikTokGrowthAgent:
    """
    Core orchestrator for TikTok content workflow.

    High-level responsibilities:
      - Plan daily videos
      - Ask other modules to generate video drafts
      - Send drafts for Telegram approval
      - Post approved videos to TikTok
      - Read comments & analytics
      - Propose improvements for the next day
    """

    def __init__(self) -> None:
        self.video_queue: List[TGAVideoDraft] = []

    # ===== PUBLIC ENTRYPOINTS (bunları digər yerlər çağıracaq) =====

    def run_daily_cycle(self) -> None:
        """
        High-level daily workflow.
        Later this will be triggered by a cron job.
        For now it's just a placeholder that we can call manually.
        """
        print("[TGA] Starting daily cycle...")
        self.plan_videos_for_today()
        self.prepare_video_drafts()
        self.send_previews_for_approval()
        print("[TGA] Daily cycle finished (waiting for approvals).")

    def handle_telegram_approval(self, draft_id: str, approved: bool) -> None:
        """
        Called when the user approves or rejects a draft via Telegram.
        """
        draft = self._find_draft(draft_id)
        if not draft:
            print(f"[TGA] Draft not found: {draft_id}")
            return

        if approved:
            draft.status = "approved"
            print(f"[TGA] Draft approved: {draft.id}")
            # Later: call TikTok API to post it
        else:
            draft.status = "rejected"
            print(f"[TGA] Draft rejected: {draft.id}")
            # Later: we can trigger regeneration here

    # ===== INTERNAL STEPS (hələ stub, sonra dolduracağıq) =====

    def plan_videos_for_today(self) -> None:
        """
        Decide how many videos to create and what themes to use.
        For now we just create 3 placeholder drafts.
        """
        print("[TGA] Planning 3 placeholder videos for today...")
        self.video_queue = []  # reset queue

        for i in range(3):
            draft = TGAVideoDraft(
                id=f"draft_{datetime.datetime.utcnow().timestamp()}_{i}",
                title=f"Cozy home textile idea #{i + 1}",
                caption="Placeholder caption – to be generated by LLM later.",
                status="draft",
                meta={"index": i},
            )
            self.video_queue.append(draft)

        print(f"[TGA] Planned {len(self.video_queue)} drafts.")

    def prepare_video_drafts(self) -> None:
        """
        Ask video_lab + trend_brain to actually build videos.
        For now this is just a stub that marks them as 'draft'.
        """
        print("[TGA] Preparing video drafts (stub)...")
        for draft in self.video_queue:
            # Later we will call:
            #   - trend_brain.suggest_style(...)
            #   - video_lab.render_video(...)
            draft.meta["render_status"] = "stub_ready"
        print("[TGA] Drafts marked as stub_ready.")

    def send_previews_for_approval(self) -> None:
        """
        Send video previews to Telegram for human approval.
        For now, we just print to console.
        """
        print("[TGA] Sending previews for approval (stub)...")
        for draft in self.video_queue:
            print(
                f"[TGA] PREVIEW -> id={draft.id} | title={draft.title} | status={draft.status}"
            )
        print("[TGA] All previews 'sent' (console stub).")

    # ===== HELPER METHODS =====

    def _find_draft(self, draft_id: str) -> TGAVideoDraft | None:
        for d in self.video_queue:
            if d.id == draft_id:
                return d
        return None
